serviceName: account_service
grpc:
  port: :5004
  development: true
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "kafka:9092" ]
  groupID: game_microservice_consumer
  initTopics: true
kafkaTopics:
  accountRegister:
    topicName: accountRegister
    partitions: 10
    replicationFactor: 1
  accountUpdate:
    topicName: accountUpdate
    partitions: 10
    replicationFactor: 1
  changePassword:
    topicName: accountChangePassword
    partitions: 10
    replicationFactor: 1
  accountBan:
    topicName: accountBan
    partitions: 10
    replicationFactor: 1
  accountDelete:
    topicName: accountDelete
    partitions: 10
    replicationFactor: 1
#  accountRegistered:
#    topicName: account_registered
#    partitions: 10
#    replicationFactor: 1
#  accountUpdated:
#    topicName: account_updated
#    partitions: 10
#    replicationFactor: 1
#  accountDeleted:
#    topicName: account_deleted
#    partitions: 10
#    replicationFactor: 1
postgres:
  driver: "postgres"
  host: "database"
  port: 5432
  user: account
  password: "3uP*SHMmk$*ri"
  dbName: account_db
redis:
  addr: "redis:6379"
  password: "zwLKq&KHb2HhphJF"
  db: 0
  poolSize: 300