serviceName: account_service
grpc:
  port: :5004
  development: true
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "localhost:9092" ]
  groupID: account_microservice_consumer
  initTopics: true
kafkaTopics:
  accountRegister:
    topicName: account_register
    partitions: 10
    replicationFactor: 1
  accountUpdate:
    topicName: account_update
    partitions: 10
    replicationFactor: 1
  changePassword:
    topicName: account_change_password
    partitions: 10
    replicationFactor: 1
  accountBan:
    topicName: account_ban
    partitions: 10
    replicationFactor: 1
  accountRegistered:
    topicName: account_registered
    partitions: 10
    replicationFactor: 1
  accountUpdated:
    topicName: account_updated
    partitions: 10
    replicationFactor: 1
  accountDeleted:
    topicName: account_deleted
    partitions: 10
    replicationFactor: 1
postgres:
  driver: "postgres"
  host: "database"
  port: 5432
  user: account
  password: "3uP*SHMmk$*ri"
  dbName: account_db
redis:
  addr: "redis:6379"
  password: "zwLKq&KHb2HhphJF"
  db: 0
  poolSize: 300