serviceName: "gateway_service"
grpc:
  authServicePort: auth_service:5003
logger:
  level: debug
  devMode: false
  encoder: json
http:
  port: :8001
  development: true
  basePath: /api/v1
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: []
jwt:
  headerAuthorization: X-AUTH-TOKEN

kafka:
  brokers: [ "kafka:9092" ]
  groupID: game_microservice_consumer
  initTopics: true
kafkaTopics:
  accountRegister:
    topicName: accountRegister
    partitions: 10
    replicationFactor: 1
  accountUpdate:
    topicName: accountUpdate
    partitions: 10
    replicationFactor: 1
  changePassword:
    topicName: accountChangePassword
    partitions: 10
    replicationFactor: 1
  accountBan:
    topicName: accountBan
    partitions: 10
    replicationFactor: 1
  accountDelete:
    topicName: accountDelete
    partitions: 10
    replicationFactor: 1
  friendInvite:
    topicName: friendInvite
    partitions: 10
    replicationFactor: 1