serviceName: authentication_service
grpc:
  port: :5003
  development: true
  accountServicePort: :5004
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "localhost:9092" ]
  groupID: auth_microservice
  initTopics: true
kafkaTopics:
  accountRegister:
    topicName: account_register
    partitions: 10
    replicationFactor: 1
  accountUpdate:
    topicName: account_update
    partitions: 10
    replicationFactor: 1
  changePassword:
    topicName: account_change_password
    partitions: 10
    replicationFactor: 1
  accountBan:
    topicName: account_ban
    partitions: 10
    replicationFactor: 1
  accountRegistered:
    topicName: account_registered
    partitions: 10
    replicationFactor: 1
  accountUpdated:
    topicName: account_updated
    partitions: 10
    replicationFactor: 1
  accountDeleted:
    topicName: account_deleted
    partitions: 10
    replicationFactor: 1
redis:
  addr: "redis:6379"
  password: "zwLKq&KHb2HhphJF"
  db: 0
  poolSize: 300
jwt:
  secret: "m%Pha8*Z6$hnUCYR@DtCY%7j!S#xceGFuC3Qd6^Nte&7&SkucS"