serviceName: authentication_service
grpc:
  port: :5003
  development: true
  accountServicePort: account_service:5004
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "kafka:9092" ]
  groupID: game_microservice_consumer
  initTopics: true
kafkaTopics:
  accountRegister:
    topicName: accountRegister
    partitions: 10
    replicationFactor: 1
  accountUpdate:
    topicName: accountUpdate
    partitions: 10
    replicationFactor: 1
  changePassword:
    topicName: accountChangePassword
    partitions: 10
    replicationFactor: 1
  accountBan:
    topicName: accountBan
    partitions: 10
    replicationFactor: 1
  accountDelete:
    topicName: accountDelete
    partitions: 10
    replicationFactor: 1
  friendInvite:
    topicName: friendInvite
    partitions: 10
    replicationFactor: 1
postgres:
  driver: "postgres"
  host: "database"
  port: 5432
  user: account
  password: "3uP*SHMmk$*ri"
  dbName: account_db
redis:
  addr: "redis:6379"
  password: "zwLKq&KHb2HhphJF"
  db: 0
  poolSize: 300
jwt:
  expireTime: "10m"
  privateKeyPath: "./rsa/jwt"
  pubKeyPath: "./rsa/jwt.pub"