name: "account"

on:
  push:
    branches:
      - develop
    paths:
      - "account/**"
      - "pkg/**"
      - ".github/workflows/account.yml"
  pull_request:
    branches:
      - develop
    paths:
      - "account/**"
      - "pkg/**"
      - ".github/workflows/account.yml"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dev-backend-game-server-account_service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # run tests for route
      - name: Run tests
        run: |-
          cd account
          go test ./...
  build_and_push:
    name: "Build Docker image and Push to Registry"
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/account.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.REGISTRY }}/dev-backend-game-server-account_service:latest
          cache-from: type=registry,ref=https://ghcr.io/CE-Final-Project/dev-backend-game-server-account_service:buildcache
          cache-to: type=registry,ref=https://ghcr.io/CE-Final-Project/dev-backend-game-server-account_service:buildcache,mode=max
