name: "auth"

on:
  push:
    paths:
      - "authentication/**"
      - "pkg/**"
      - ".github/workflows/auth.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # run tests for route
      - name: Run tests
        run: |-
          cd authentication
          go test ./...
  build_and_push:
    name: "Build Docker image and Push to Registry"
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Docker/auth.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-game-server-auth_service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-game-server-auth_service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-game-server-auth_service:buildcache,mode=max
  update_server:
    name: "SSH update image on the server"
    needs:
      - build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: testing ssh on server connection
        uses: appleboy/ssh-action@master
        with:
          host: game.kenta420.studio
          username: analytic
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
            cd backend_game_server
            git pull origin main
            git status
